### ISSUE TITLE
Tasks about updating links in spring.io

### ISSUE THREAD

**Issue by backwind1233** [Azure-Samples/azure-spring-boot-samples#40]
**Context**
We should update the link of  https://spring.io/projects/spring-cloud-azure#samples  when sample is adjusted.
Now the link in https://spring.io/projects/spring-cloud-azure#samples is [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples).
<img width="866" alt="image" src="https://user-images.githubusercontent.com/4465723/167233628-e9ec69c6-091e-4cda-b652-f4d1c40256ad.png">

**Task**
1. Rename folder name from aad to azure active directory
  now folder [name](https://github.com/Azure-Samples/azure-spring-boot-samples) aad is not consistant with offical [doc](https://docs.microsoft.com/en-us/azure/active-directory/), may be confusing.
    - [ ] rename folder @backwind1233 
    - [x] Update spring reference yaml 
    - [x] update links in samples, azure-sdk-for-java,azure-dev-docs-pr
- [x] Update sample links in [spring.io](https://spring.io/projects/spring-cloud-azure)

**Comment by stliu** [comment]
@chenrujun I'm reassigning this to you since this is part of our samples visibility tasks

**Comment by saragluna** [comment]
Closing this issue now.
